AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend for uploading files to Amazon S3 via Uppy / Companion.

Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowMethods: "'OPTIONS, GET, PUT, POST'"
      AllowOrigin: "'*'"

Parameters:
  CognitoAuthorizerArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Reference to Cognito UserPool for the stage
    Default: CognitoAuthorizerArn
  ExternalCognitoAuthorizerArn:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Reference to ARN of ExternalUsers UserPool
    Default: ExternalCognitoAuthorizerArn
  CustomDomain:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Description: Custom API to connect this lambda to
    Default: CustomDomain
  S3UploadBucket:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: /NVA/PublicationData
    Description: S3 Bucket to upload files to
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain
    Default: upload


Resources:
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
  UploadApi:
    Type: AWS::Serverless::Api
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        'Fn::Transform':
          Name: AWS::Include
          Parameters:
            Location: ./docs/openapi.yaml

  CreateUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: create-upload
      Environment:
        Variables:
          S3_UPLOAD_BUCKET: !Ref  S3UploadBucket
          ALLOWED_ORIGIN:  '*'
      Handler: no.unit.nva.fileupload.CreateUploadHandler::handleRequest
      Runtime: java17
      MemorySize: 1408
      Role: !GetAtt UploadExecutionRole.Arn
      Events:
        CreateEvent:
          Type: Api
          Properties:
            Path: /create
            Method: post
            RestApiId: !Ref UploadApi

  ListPartsUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: list-parts
      Environment:
        Variables:
          S3_UPLOAD_BUCKET: !Ref  S3UploadBucket
          ALLOWED_ORIGIN:  '*'
      Handler: no.unit.nva.fileupload.ListPartsHandler::handleRequest
      Runtime: java17
      MemorySize: 1408
      Role: !GetAtt UploadExecutionRole.Arn
      Events:
        ListEvent:
          Type: Api
          Properties:
            Path: /listparts
            Method: post
            RestApiId: !Ref UploadApi

  PrepareUploadPartFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: prepare-upload-part
      Environment:
        Variables:
          S3_UPLOAD_BUCKET: !Ref  S3UploadBucket
          ALLOWED_ORIGIN:  '*'
      Handler: no.unit.nva.fileupload.PrepareUploadPartHandler::handleRequest
      Runtime: java17
      MemorySize: 1408
      Role: !GetAtt UploadExecutionRole.Arn
      Events:
        PrepareEvent:
          Type: Api
          Properties:
            Path: /prepare
            Method: post
            RestApiId: !Ref UploadApi

  AbortUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: abort-multipart-upload
      Environment:
        Variables:
          S3_UPLOAD_BUCKET: !Ref  S3UploadBucket
          ALLOWED_ORIGIN:  '*'
      Handler: no.unit.nva.fileupload.AbortMultipartUploadHandler::handleRequest
      Runtime: java17
      MemorySize: 1408
      Role: !GetAtt UploadExecutionRole.Arn
      Events:
        AbortEvent:
          Type: Api
          Properties:
            Path: /abort
            Method: post
            RestApiId: !Ref UploadApi

  CompleteUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: complete-upload
      Environment:
        Variables:
          S3_UPLOAD_BUCKET: !Ref  S3UploadBucket
          ALLOWED_ORIGIN:  '*'
      Handler: no.unit.nva.fileupload.CompleteUploadHandler::handleRequest
      Runtime: java17
      MemorySize: 1408
      Role: !GetAtt UploadExecutionRole.Arn
      Events:
        CompleteEvent:
          Type: Api
          Properties:
            Path: /complete
            Method: post
            RestApiId: !Ref UploadApi

  UploadApiMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Sub api.${CustomDomain}
      RestApiId: !Ref UploadApi
      Stage: !Ref UploadApi.Stage

  UploadExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: manage-uploads
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucketMultipartUploads
                  - s3:AbortMultipartUpload
                  - s3:ListMultipartUploadParts
                Resource:
                  - !Sub 'arn:aws:s3:::${S3UploadBucket}'
                  - !Sub 'arn:aws:s3:::${S3UploadBucket}/*'

  #============================ Deploy API ============================================================================#
  # This solves the problem described here:
  # https://stackoverflow.com/questions/41423439/cloudformation-doesnt-deploy-to-api-gateway-stages-on-update
  #====================================================================================================================#

  ApiGatewayCreateDeploymentLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: ApiGatewayAdmin
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:POST
                Resource: !Sub 'arn:aws:apigateway:${AWS::Region}::/restapis/${UploadApi}/deployments'

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-lambda-function-code-cfnresponsemodule.html
  ApiGatewayCreateDeploymentLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      MemorySize: 128
      Timeout: 30
      Role: !GetAtt ApiGatewayCreateDeploymentLambdaRole.Arn
      Runtime: python3.8
      Code:
        ZipFile: |
          import json, boto3
          import cfnresponse
          client = boto3.client('apigateway')

          def lambda_handler(event, context):
            responseData = {}
            responseStatus = cfnresponse.SUCCESS
            if event['RequestType'] == 'Update':
              try:
                properties = event['ResourceProperties']
                response = client.create_deployment(
                  restApiId=properties['RestApiId'],
                  stageName=properties['StageName'],
                  description='Deployed from Custom Resource'
                )
              except:
                responseStatus = cfnresponse.FAILED

            cfnresponse.send(event, context, responseStatus, responseData)

  ApiGatewayCreateDeploymentCustomResource:
    DependsOn: UploadApi
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt ApiGatewayCreateDeploymentLambda.Arn
      RestApiId: !Ref UploadApi
      StageName: !Ref UploadApi.Stage
      Timestamp: '${BUILD_TIMESTAMP}'
      AuthorizerArn: !Ref CognitoAuthorizerArn
